name: aur-publish

on:
  workflow_dispatch:
  push:
    tags: 
      - "v[12].[0-9]+.[0-9]+"       # Match any semantic versioning tag

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Publish AUR package
        uses: ulises-jeremias/github-actions-aur-publish@v1
        with:
          pkgname: ghostty_wrapper
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: ed25519
          update_pkgver: false
